setwd("D:/Arjun/Desktop/Learning/Coursera/Signature Track/Working Directory")

power <- read.table("household_power_consumption.txt",header=T, sep=";")
power$dt <- as.Date(power$Date, format = "%m/%d/%Y")
pow <- subset(power, as.Date(power$dt)==as.Date('2007-02-01') | as.Date(power$dt)==as.Date('2007-02-02'))
pow$day<- weekdays(as.Date(pow$dt,'%d-%m-%Y'))
pow$gap<- as.numeric(as.character(pow$Global_active_power))
pow$grp<- as.numeric(as.character(pow$Global_reactive_power))
pow$vol<- as.numeric(as.character(pow$Voltage))
pow$gi<- as.numeric(as.character(pow$Global_intensity))
pow$sm1<- as.numeric(as.character(pow$Sub_metering_1))
pow$sm2<- as.numeric(as.character(pow$Sub_metering_2))
pow$sm3<- as.numeric(as.character(pow$Sub_metering_3))
pow$TD <- strptime(paste(pow$Date, pow$Time, sep=","), format="%m/%d/%Y,%H:%M:%S")

head(pow)
summary(pow$Time)
str(pow)


par(mfrow = c(2,2))
plot(pow$TD, pow$gap, main= "", xlab = "", ylab = "Global Active Power", type = "n") 
lines(pow$TD, pow$gap) 
plot(pow$TD, pow$vol, main= "", xlab = "datetime", ylab = "", type = "n") 
lines(pow$TD, pow$vol) 
plot(pow$TD, pow$sm3, main= "", xlab = "", ylab = "Energy sub metering", type = "n",ylim=c(0, 30)) 
lines(pow$TD, pow$sm1, col = "black") 
lines(pow$TD, pow$sm2, col = "red") 
lines(pow$TD, pow$sm3, col = "blue") 
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black", "red", "blue"), bty = "n")
plot(pow$TD, pow$grp, main= "", xlab = "datetime", ylab = "", type = "n") 
lines(pow$TD, pow$grp) 

dev.copy(png, file = "plot4.png", width=480, height=480)
dev.off()
